[Thu Nov 07 06:01:37.122662 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592] [2024-11-07 06:01:37,122] ERROR in app: Exception on / [GET]
[Thu Nov 07 06:01:37.122694 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592] Traceback (most recent call last):
[Thu Nov 07 06:01:37.122696 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592]   File "/var/www/dinjou.com/pages/rds/.venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
[Thu Nov 07 06:01:37.122699 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592]     response = self.full_dispatch_request()
[Thu Nov 07 06:01:37.122701 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592]   File "/var/www/dinjou.com/pages/rds/.venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
[Thu Nov 07 06:01:37.122703 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592]     rv = self.handle_user_exception(e)
[Thu Nov 07 06:01:37.122705 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592]   File "/var/www/dinjou.com/pages/rds/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
[Thu Nov 07 06:01:37.122708 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592]     rv = self.dispatch_request()
[Thu Nov 07 06:01:37.122710 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592]   File "/var/www/dinjou.com/pages/rds/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
[Thu Nov 07 06:01:37.122712 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
[Thu Nov 07 06:01:37.122714 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592]   File "/var/www/dinjou.com/pages/rds/app.py", line 84, in index
[Thu Nov 07 06:01:37.122716 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592]     if connection.is_connected():
[Thu Nov 07 06:01:37.122718 2024] [wsgi:error] [pid 1156572:tid 139216239461952] [client 100.100.155.96:42592] AttributeError: 'NoneType' object has no attribute 'is_connected'
[Thu Nov 07 06:05:31.019136 2024] [wsgi:error] [pid 1157811:tid 139216239461952] [client 100.100.155.96:45418] mod_wsgi (pid=1157811): Failed to exec Python script file '/var/www/dinjou.com/pages/rds/myapp.wsgi'.
[Thu Nov 07 06:05:31.019168 2024] [wsgi:error] [pid 1157811:tid 139216239461952] [client 100.100.155.96:45418] mod_wsgi (pid=1157811): Exception occurred processing WSGI script '/var/www/dinjou.com/pages/rds/myapp.wsgi'.
[Thu Nov 07 06:05:31.024173 2024] [wsgi:error] [pid 1157811:tid 139216239461952] [client 100.100.155.96:45418] Traceback (most recent call last):
[Thu Nov 07 06:05:31.024193 2024] [wsgi:error] [pid 1157811:tid 139216239461952] [client 100.100.155.96:45418]   File "/var/www/dinjou.com/pages/rds/myapp.wsgi", line 15, in <module>
[Thu Nov 07 06:05:31.024197 2024] [wsgi:error] [pid 1157811:tid 139216239461952] [client 100.100.155.96:45418]     from app import app as application
[Thu Nov 07 06:05:31.024207 2024] [wsgi:error] [pid 1157811:tid 139216239461952] [client 100.100.155.96:45418]   File "/var/www/dinjou.com/pages/rds/app.py", line 42
[Thu Nov 07 06:05:31.024213 2024] [wsgi:error] [pid 1157811:tid 139216239461952] [client 100.100.155.96:45418]     connection.close()
[Thu Nov 07 06:05:31.024218 2024] [wsgi:error] [pid 1157811:tid 139216239461952] [client 100.100.155.96:45418] IndentationError: unexpected indent
